// Removes ALL storefront test fixtures (Phase 1 + Phase 2)
require('/app/node_modules/dotenv').config({ path: '/app/backend/.env' })
const { MongoClient } = require('/app/node_modules/mongodb')
;(async () => {
  const client = new MongoClient(process.env.MONGO_URL)
  await client.connect()
  const db = client.db(process.env.DB_NAME || 'test')
  const u = await db.collection('webUsers').deleteMany({ $or: [{ __seedTest: true }, { email: { $regex: /@(example|test)\.(com|org)$/i } }] })
  const o = await db.collection('webOrders').deleteMany({})
  const t = await db.collection('webWalletTxns').deleteMany({ webUserId: { $in: ['webuser-storetest-fixed', 'webuser-storebuyer-fixed', 'webuser-storebroke-fixed'] } })
  const c = await db.collection('cpanelAccounts').deleteMany({ __seedTest: true })
  console.log('cleanup webUsers=', u.deletedCount, 'webOrders=', o.deletedCount, 'txns=', t.deletedCount, 'cpanelAccounts(seed)=', c.deletedCount)
  await client.close()
})().catch(e => { console.error('ERR', e.message); process.exit(1) })
