// Removes the storefront test fixtures seeded by seed_storetest.js
require('/app/node_modules/dotenv').config({ path: '/app/backend/.env' })
const { MongoClient } = require('/app/node_modules/mongodb')
;(async () => {
  const client = new MongoClient(process.env.MONGO_URL)
  await client.connect()
  const db = client.db(process.env.DB_NAME || 'test')
  const u = await db.collection('webUsers').deleteMany({ __seedTest: true })
  const o = await db.collection('webOrders').deleteMany({ __seedTest: true })
  const t = await db.collection('webWalletTxns').deleteMany({ webUserId: 'webuser-storetest-fixed' })
  // also remove any signup users created during agent testing (example.com test addresses)
  const e = await db.collection('webUsers').deleteMany({ email: { $regex: /@(example|test)\.(com|org)$/i } })
  console.log('cleanup webUsers(seed)=', u.deletedCount, 'webOrders=', o.deletedCount, 'txns=', t.deletedCount, 'webUsers(test-emails)=', e.deletedCount)
  await client.close()
})().catch(e => { console.error('ERR', e.message); process.exit(1) })
